#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
英雄无敌 - 多语言支持模块
"""

# 语言支持类
class LanguageSupport:
    """游戏多语言支持"""
    
    def __init__(self, language="zh"):
        self.language = language
        self.set_language(language)
    
    def set_language(self, language):
        """设置当前语言"""
        self.language = language
        if language == "en":
            self.texts = self._get_english_texts()
        else:
            self.texts = self._get_chinese_texts()
        
        # 设置语言特定的格式化函数
        self.format_functions = {
            "position_format": self._get_position_format,
            "hero_marker": self._get_hero_marker,
            "event_text": self._get_event_text,
            "skill_brackets": self._get_skill_brackets,
            "equipment_name": self._get_equipment_name
        }
    
    def _get_chinese_texts(self):
        """获取中文文本"""
        return {
            "welcome_title": "欢迎来到《英雄无敌》文字冒险游戏",
            "welcome_desc1": "游戏说明：",
            "welcome_desc2": "1. 你将扮演一位英雄，在10格直线地图上冒险",
            "welcome_desc3": "2. 每一步都可能遇到随机事件",
            "welcome_desc4": "3. 到达终点即为胜利，血量归零即为失败",
            "welcome_desc5": "4. 祝你好运，英雄！",
            "continue_prompt": "按回车键继续...",
            "hero_creation": "创建你的英雄",
            "enter_name": "请输入你的英雄名字: ",
            "name_empty": "名字不能为空，请重新输入！",
            "game_start": "游戏开始",
            "game_over": "游戏结束",
            "victory": "恭喜通关！",
            "restart": "是否重新开始游戏？(y/n): ",
            "yes_options": ["y", "Y", "yes", "是"],
            "invalid_choice": "无效选择，请输入 y 或 n！",
            "goodbye": "感谢游玩《英雄无敌》，再见！",
            # 稀有度名称
            "rarity_common": "普通",
            "rarity_uncommon": "优秀",
            "rarity_rare": "稀有",
            "rarity_epic": "史诗",
            "rarity_legendary": "传说",
            "hero_info": "英雄信息",
            "name": "名字",
            "hp": "血量",
            "max_hp": "最大血量",
            "attack": "攻击力",
            "defense": "防御力",
            "gold": "金币",
            "exp": "经验值",
            "level": "等级",
            "potions": "药剂",
            "position": "位置",
            "skills": "技能",
            "map": "地图",
            "forward": "向前移动",
            "view_status": "查看状态",
            "view_history": "查看冒险历程",
            "use_potion": "使用生命药剂",
            "shop": "商店 (消耗金币)",
            "choose_action": "选择你的行动:",
            "enter_choice": "请输入选择",
            "hero_victory": "你击败了",
            "monster_attack": "对你造成了",
            "damage": "点伤害",
            "you_attack": "你对",
            "caused_damage": "造成了",
            "point_damage": "点伤害",
            "heal": "恢复了",
            "point_hp": "点血量",
            "battle_start": "战斗开始！",
            "battle_victory": "你击败了",
            "got_exp": "获得了",
            "exp_points": "经验值和",
            "gold_coins": "金币",
            "level_up": "恭喜！你升到了",
            "level": "级",
            "max_hp_up": "血量上限+20, 攻击力+5, 防御力+2",
            "newbie_village": "新手村",
            "village_welcome": "欢迎来到新手村",
            "village_desc": "村长看起来很高兴见到你，并向你走来...",
            "chief_speak": "村长：'欢迎，年轻的英雄！在你踏上冒险之旅前，",
            "chief_speak2": "       我建议你先在村里熟悉一下。'",
            "training_ground": "训练场",
            "village_shop": "商店",
            "clinic": "诊所",
            "chief_home": "村长家",
            "leave_village": "离开村庄 - 开始冒险",
            "current_location": "当前位置：村庄广场",
            "areas": "可行动区域：",
            "training_ground_desc": "训练场 - 学习战斗技巧",
            "shop_desc": "商店 - 购买基础装备",
            "clinic_desc": "诊所 - 治疗伤口",
            "chief_home_desc": "村长家 - 获得建议",
            "instructor": "教官：'我是村里的格斗教官，我来教你一些基础技巧。'",
            "combat_training": "学习战斗技巧（模拟战斗，无危险）",
            "return_village": "返回村庄广场",
            "training_start": "教官：'很好！让我们来练习一下。'",
            "training_dummy": "出现了一个训练假人...",
            "safe_battle": "这是一场无危险的模拟战斗！",
            "instructor_tip1": "教官：'攻击时可以选择普通攻击或使用技能。'",
            "instructor_tip2": "教官：'记得合理使用药剂和治疗术恢复生命值。'",
            "instructor_tip3": "教官：'不同的技能有不同的效果，要灵活运用！'",
            "training_complete": "训练完成！你获得了5点经验值。",
            "shopkeeper": "店主：'欢迎光临！我这里有一些对新手有用的物品。'",
            "your_gold": "你的金币:",
            "shop_items": "商店商品：",
            "health_potion": "生命药剂",
            "beginner_weapon": "新手武器 +5攻击力",
            "beginner_armor": "新手护甲 +3防御力",
            "leave_shop": "离开商店",
            "buy_potion": "你购买了一瓶生命药剂！",
            "buy_weapon": "你购买了新手武器，攻击力+5！",
            "buy_armor": "你购买了新手护甲，防御力+3！",
            "shopkeeper_goodbye": "店主：'感谢光临，下次再来！'",
            "not_enough_gold": "金币不足或无效选择！",
            "doctor": "医生：'哦，一位新的冒险者！让我给你做个检查。'",
            "doctor_good_health": "医生：'你的身体状况很好，不需要治疗。'",
            "doctor_tip": "医生：'但还是要提醒你，冒险时注意安全！'",
            "doctor_heal": "医生：'让我帮你治疗一下...'",
            "full_heal": "治疗后，你的血量完全恢复了！",
            "elder": "村长：'啊，年轻的英雄，你有很多问题想问吗？'",
            "advice_adventure": "关于冒险的建议",
            "advice_level": "关于技能和等级",
            "advice_combat": "关于战斗技巧",
            "leave": "离开",
            "elder_adventure_tip": "村长：'冒险时要时刻注意你的血量，' '       尤其是遇到Boss时更要谨慎。' '       地图上充满了各种随机事件，' '       有些会给你带来好处，有些则很危险。'",
            "elder_level_tip": "村长：'每次升级你的属性都会提升，' '       每3级你还有机会学会新技能。' '       技能会让你在战斗中更有优势，' '       好好利用它们！'",
            "elder_combat_tip": "村长：'战斗中你可以选择攻击、使用药剂或释放技能。' '       怪物的强度会随着你的等级提高而增强，' '       所以不要掉以轻心！' '       Boss比普通怪物更强大，但奖励也更丰厚。'",
            "elder_goodbye": "村长：'祝你冒险顺利！'",
            "elder_not_hear": "村长：'我没听清楚你想了解什么。'",
            "leave_village_msg": "村长：'祝你好运，勇敢的冒险者！'",
            "leave_village_msg2": "你告别了村民，踏上了冒险之路...",
            "step_forward": ">>> 你向前走了一步...",
            "mine_trap": "糟糕！你踩到了地雷，损失了",
            "actual_damage": "点血量！",
            "dodge_mine": "你敏锐地察觉到了地雷，及时闪避，没有受到伤害！",
            "find_bun": "幸运！你发现了一个魔法包子，恢复了",
            "find_spring": "你发现了一处生命之泉，完全恢复了所有血量！",
            "find_chest": "你发现了一个宝箱，获得了",
            "coins": "枚金币！",
            "merchant": "你遇到了一位神秘的商人！",
            "merchant_speak": "商人: '旅行者，我有一些好东西，要看看吗？'",
            "no_gold": "商人: '看来你囊中羞涩，下次再来吧！'",
            "learn_skill": "学习技能",
            "learn_skill_success": "奇迹发生！你学会了",
            "mysterious_teacher": "你遇到了一位神秘的老师！他可以教你一个技能。",
            "skill_name": "】技能！",
            "skill_effect": "效果: ",
            "find_potion": "你发现了一瓶生命药剂！",
            "trap": "你掉入了陷阱，损失了",
            "dodge_trap": "你敏锐地察觉到了陷阱，及时闪避，没有受到伤害！",
            "safe_move": "平安无事，继续前进。",
            "encounter_monster": "你遇到了一只怪物！",
            "encounter_boss": "你遇到了一只强大的Boss！",
            "poison": "使用了生命药剂，恢复了",
            "use_heal": "释放了治疗术，恢复了",
            "full_hp_no_heal": "你的血量已满，不需要治疗！",
            "fireball": "你释放了火球术，对",
            "fireball_damage": "造成了",
            "fireball_crit": "火球术暴击！你对",
            "fireball_critical": "火球术暴击！你对",
            "crit": "暴击！你对",
            "lifesteal": "吸血效果恢复了",
            "dodge": "你闪避了",
            "no_damage": "的攻击，没有受到伤害！",
            "boss_skill_damage": "释放了强力攻击，对你造成了",
            "game_over_msg": "倒在了冒险途中...",
            "try_again": "再接再厉，英雄！",
            "victory_msg": "成功完成了冒险！",
            "final_status": "最终状态",
            "real_hero": "你是一位真正的英雄！",
            "monsters_defeated": "击败怪物",
            "total_gold": "获得金币",
            "skills_learned": "已学技能",
            "adventure_history": "冒险历程",
            "no_history": "还没有任何冒险记录...",
            "your_journey": "你的冒险历程:",
            "damage_defense": "实际伤害",
            "no_victory_heal": "吸血技能让你在战斗中保持了优势！",
            "victory_full_heal": "胜利完全恢复了所有血量！",
            "victory_heal": "胜利恢复了",
            "boss_defeated": "击败了强大的",
            "hero_medal": "获得了【英雄徽章】！",
            "boss_lifesteal": "吸血技能让你在Boss战中保持了优势！",
            "level_up_reward": "升级奖励：你学会了【",
            "all_skills_learned": "你已经学会了所有技能！",
            "fireball_desc": "战斗中可以释放强力魔法攻击，也能触发吸血",
            "lifesteal_desc": "每次攻击都会回复伤害值30%的血量",
            # 新增技能描述
            "combo_desc": "连续攻击2次，每次造成50%伤害",
            "shield_desc": "下次受到伤害减少50%",
            "berserk_desc": "下3回合攻击提升50%，防御降低50%",
            "focus_desc": "下次攻击必中且暴击",
            # 新技能效果描述
            "combo_total_damage": "连斩总伤害",
            "focus_critical": "专注暴击",
            "shield_activated": "护盾已激活，下次受到伤害减少50%",
            "berserk_activated": "进入狂暴状态",
            "berserk_attack_up": "攻击力提升50%",
            "berserk_defense_down": "防御力降低50%",
            "focus_activated": "专注状态已激活",
            "focus_next_attack": "下次攻击必中且暴击",
            "berserk_defense_active": "狂暴状态：防御力降低",
            "shield_reduced_damage": "护盾减少伤害至",
            "berserk_attack_active": "狂暴状态：攻击力提升",
            "berserk_remaining": "狂暴剩余回合",
            "berserk_turns": "回合",
            "berserk_ended": "狂暴状态结束",
            "dodge_desc": "20%概率完全避免伤害",
            "crit_desc": "15%概率造成双倍伤害",
            "heal_desc": "战斗中可以恢复25-40点血量",
            "unknown_effect": "未知效果",
            "choose_language": "请选择语言/Please select language",
            "chinese": "中文",
            "english": "English",
            "unit_coins": "枚",
            "unit_monsters": "只",
            "unit_skills": "个",
            "block_separator": "="*50,
            "item_separator": ": ",
            "round": "第",
            "normal_attack": "普通攻击",
            "remaining": "剩余",
            "cast_fireball": "释放火球术",
            "locked": "未解锁",
            "cast_healing": "释放治疗术",
            # 新技能动作文本
            "cast_combo": "使用连斩",
            "cast_shield": "使用护盾",
            "cast_berserk": "进入狂暴",
            "cast_focus": "专注",
            "invalid_action": "无法执行该操作，改为普通攻击！",
            "your_hp": "你的血量",
            "monster_hp": "怪物血量",
            "boss_hp": "Boss血量",
            "boss_powerful_attack": "释放了强力攻击，对你造成了",
            "restore": "恢复",
            "permanent": "永久",
            "strength_potion": "力量药水",
            "defense_scroll": "防御卷轴",
            "special_price": "商店特惠价",
            "no_potions": "你没有药剂了！",
            "already_at_end": "你已经到达终点了！",
            "danger_encounter": "危险！遭遇了强大的",
            "boss_battle_start": "Boss战开始！",
            "boss_victory": "你击败了强大的",
            "hero_badge": "获得了【英雄徽章】！",
            "defeat_boss": "击败Boss",
            "lifesteal_advantage": "吸血技能让你在Boss战中保持了优势！",
            "dodge_attack": "你闪避了",
            "dodge_success": "的攻击，没有受到伤害！",
            "healing_spell": "你释放了治疗术，恢复了",
            # 装备系统
            "weapon": "武器",
            "armor": "防具",
            "accessory": "饰品",
            "none": "无",
            "inventory": "背包",
            "inventory_empty": "你的背包是空的！",
            "equipment_management": "装备管理",
            "current_weapon": "当前武器",
            "current_armor": "当前防具",
            "current_accessory": "当前饰品",
            "current_equipment": "当前装备",
            "view_inventory": "查看背包",
            "equip_item": "装备物品",
            "unequip_item": "卸下装备",
            "unequip_weapon": "卸下武器",
            "unequip_armor": "卸下防具",
            "unequip_accessory": "卸下饰品",
            "return_game": "返回游戏",
            "select_item_to_equip": "选择要装备的物品编号",
            "invalid_item": "无效的物品编号！",
            "invalid_item_type": "无效的装备类型！",
            "no_equipped_item": "该栏位没有装备！",
            "equip_success": "成功装备",
            "unequip_success": "成功卸下",
            "equipment_shop": "装备商店",
            "select_category": "选择商品类别",
            "weapons": "武器",
            "armors": "防具",
            "accessories": "饰品",
            "buy": "购买",
            "back": "返回",
            "buy_success": "成功购买",
            "mysterious_merchant": "你遇到了一位神秘的商人！",
            "treasure_chest_with_equipment": "你发现了一个闪亮的宝箱！",
            # 难度和地图系统
            "select_map_difficulty": "选择地图和难度",
            "select_difficulty": "选择难度",
            "difficulty_easy": "简单",
            "difficulty_normal": "普通",
            "difficulty_hard": "困难",
            "difficulty_nightmare": "噩梦",
            "select_map_type": "选择地图类型",
            "select_map_type": "选择你冒险的地图类型",
            "map_plains": "平原",
            "map_forest": "森林",
            "map_desert": "沙漠",
            "map_dungeon": "地牢",
            "map_mountain": "山脉",
            "plains_desc": "平坦的草原，适合新手",
            "forest_desc": "神秘的森林，有很多草药和野兽",
            "desert_desc": "炎热的沙漠，有危险的生物",
            "dungeon_desc": "阴森的地牢，强大的敌人",
            "mountain_desc": "险峻的山脉，有巨人和龙",
            "difficulty": "难度",
            "map_type": "地图类型",
            "map_length": "地图长度",
            "game_settings": "游戏设置",
            # 新事件文本
            "thorns_damage": "你被荆棘刺伤，损失了",
            "find_herbs": "你发现了治愈草药，恢复了",
            "dehydration": "你感到极度脱水，损失了",
            "find_oasis": "你发现了沙漠绿洲，恢复了",
            "dungeon_trap": "你触发了地牢陷阱，损失了",
            "encounter_ghost": "你遇到了",
            "mountain_hazard": "你遭遇了雪崩/落石，损失了",
            "find_gem": "你发现了宝石，获得了",
            "ghost_drop_equipment": "鬼魂消散时掉落了装备！",
            "ghost_dissipate": "鬼魂消散在虚空中...",
            "encounter_ghost": "你遇到了一只鬼魂！",
            # 新手村额外文本
            "village_clinic": "诊所",
            "elder_advice_short": "长老建议",
            "start_adventure": "开始冒险",
            "hp_recovered": "你的血量已完全恢复！",
            "training_desc": "训练场可以让你练习战斗技巧，提升经验值。",
            "practice_combat": "练习战斗",
            "learn_skill_short": "学习技能",
            # 技能名称
            "fireball_skill": "火球术",
            "healing_skill": "治疗术",
            "critical_skill": "暴击",
            "lifesteal_skill": "吸血",
            "dodge_skill": "闪避",
            # 新增技能
            "combo_skill": "连斩",
            "shield_skill": "护盾",
            "berserk_skill": "狂暴",
            "focus_skill": "专注",
            "critical_hit": "暴击！你对",
            "lifesteal_effect": "吸血效果恢复了",
            # 稀有度名称
            "rarity_common": "普通",
            "rarity_uncommon": "优秀",
            "rarity_rare": "稀有",
            "rarity_epic": "史诗",
            "rarity_legendary": "传说",
            "return_to_village": "返回村庄",
            "practice_start": "练习开始！你的对手是",
            "practice_victory": "练习结束！你击败了",
            "practice_reward": "获得20经验值和10金币！",
            "learn_skill_cost": "学习技能需要花费",
            "trainer_introduction": "训练师说：我可以教你一些有用的技能。",
            "confirm_learn": "确定要学习吗？(y/n)",
            "cancel_learn": "你取消了学习。",
            "shopkeeper_greeting": "店主：'欢迎光临商店！要买点什么？'",
            "how_many": "购买数量",
            "exit_shop": "离开商店",
            "use_potion_short": "使用药剂",
            "healing_spell_short": "治疗术",
            "merchant_desc": "商人：'旅行者，我有各种好东西，要看看吗？'",
            "buy_equipment": "购买装备",
            "buy_equipment_short": "购买装备",
            "leave_merchant": "离开",
            "merchant_encounter": "遇到商人",
            "mysterious_merchant_encounter": "神秘商人",
            "mysterious_merchant_desc": "神秘商人：'勇敢的冒险者，我有稀有装备出售...'",
            "empty_inventory": "背包为空",
            "enter_item_number": "输入物品编号",
            "return_to_game": "返回游戏",
            "treasure_chest": "宝箱",
            "treasure_chest_desc": "你发现了一个神秘的宝箱，里面可能藏着珍贵的装备！",
            "no_events_yet": "还没有任何冒险记录...",
            "clinic_offer": "医生：'我可以治疗你，恢复",
            "clinic_cost": "治疗费用",
            "confirm_treatment": "确定治疗吗？(y/n)",
            "cancel_treatment": "你取消了治疗。",
            "hp_full": "医生：'你的身体状况很好，不需要治疗。'",
            "treatment_success": "治疗后，你的血量完全恢复了！",
            "elder_advice_title": "长老建议",
            "elder_desc": "长老：'年轻的英雄，让我给你一些建议吧。'",
            "restart_prompt": "是否重新开始游戏",
            # 训练假人名称
            "training_dummy": "训练假人",
            # 长老建议
            "elder_advice_1": "记住，药剂是救命的关键，不要吝啬使用！",
            "elder_advice_2": "升级时要谨慎选择技能，不同的技能适合不同的战斗风格。",
            "elder_advice_3": "高难度地图敌人更强，但奖励也更丰厚。",
            "elder_advice_4": "不同的地图有不同的危险和机遇，选择适合自己的。",
            "elder_advice_5": "装备可以大幅提升你的战斗力，尽可能收集更好的装备！",
            "elder_advice_6": "Boss战每3回合会释放强力攻击，注意保持血量！",
            # 怪物名称
            "monster_goblin": "哥布林",
            "monster_skeleton": "骷髅兵",
            "monster_wolf": "野狼",
            "monster_bandit": "强盗",
            "monster_slime": "史莱姆",
            "monster_pixie": "小妖精",
            "monster_orc_warrior": "兽人战士",
            "monster_bandit_leader": "强盗头目",
            "monster_dark_mage": "黑暗法师",
            "monster_elite_assassin": "精英刺客",
            "monster_troll": "巨魔",
            "monster_beast": "野兽",
            "monster_spider": "蜘蛛",
            "monster_scorpion": "蝎子",
            "monster_sand_worm": "沙虫",
            "monster_golem": "石像鬼",
            "monster_ghost": "鬼魂",
            "monster_demon": "恶魔",
            "monster_giant": "巨人",
            "monster_dragon": "龙",
            "monster_titan": "泰坦",
            # Boss名称
            "boss_lesser_demon_leader": "小恶魔首领",
            "boss_cave_troll": "洞穴巨魔",
            "boss_shadow_spider": "暗影蜘蛛",
            "boss_dark_lord": "暗黑领主",
            "boss_frost_queen": "冰霜女王",
            "boss_fire_lizard": "火焰巨蜥",
            "boss_ancient_dragon": "远古巨龙",
            "boss_abyss_demon": "深渊恶魔",
            "boss_death_knight": "死亡骑士",
            "boss_chaos_wizard": "混沌巫师",
            # 鬼魂名称
            "ghost_wandering": "游荡的鬼魂",
            "ghost_vengeful": "怨灵",
            "ghost_soul_guardian": "灵魂守卫",
            # 游戏消息
            "ghost_no_exp_warning": "警告：击败鬼魂无法获得经验值！",
            "ghost_dissipate_nothing": "鬼魂消散了，什么也没留下...",
            "ghost_leave_equipment": "鬼魂留下了一个神秘的装备！",
            "victory_full_restore": "胜利完全恢复了所有血量！",
            # 技能名称
            "lifesteal_skill_name": "吸血",
            # 装备消息
            "no_equipment_in_slot": "该位置没有装备！",
            "found_equipment": "你发现了：",
            "equipment_stats": "属性：",
            "used_potion_event": "使用了药剂，恢复了",
            "hp_points_event": "点血量",
            "learned_skill_event": "学会了技能: ",
            "found_equipment_event": "发现了 ",
            "defeat_boss_event": "击败Boss",
            "got_gold_from_ghost": "从鬼魂处获得了",
            "got_gold_from_ghost_en": "Got ",
            "skill_bracket_zh": "【",
            "skill_bracket_zh_end": "】",
            "skill_bracket_en": "[",
            "skill_bracket_en_end": "]",
            # 存档系统
            "main_menu": "主菜单",
            "new_game": "新游戏",
            "load_game": "加载存档",
            "exit_game": "退出游戏",
            "save_game": "保存游戏",
            "save_and_exit": "保存并退出",
            "save_success": "游戏已保存到槽位",
            "save_failed": "保存失败",
            "load_success": "存档已加载",
            "load_failed": "加载存档失败",
            "no_save_slot": "该槽位没有存档",
            "save_slot_title": "选择存档槽位",
            "save_slot_empty": "槽位",
            "save_slot_info": "英雄",
            "save_slot_level": "等级",
            "save_slot_map": "地图",
            "save_slot_difficulty": "难度",
            "save_slot_position": "进度",
            "save_slot_time": "保存时间",
            "delete_save": "删除存档",
            "delete_confirm": "确认删除该存档吗？(y/n)",
            "delete_success": "存档已删除",
            "save_corrupted": "存档文件损坏",
            "select_slot_to_load": "选择要加载的存档槽位",
            "select_slot_to_save": "选择要保存的槽位",
            "return_to_main": "返回主菜单",
            "current_save": "当前存档",
            "overwrite_save": "覆盖已有存档",
            "empty_slot": "空槽位",
            # 统计系统
            "view_statistics": "查看统计",
            "play_time": "游戏时长",
            "total_steps": "总移动步数",
            "battle_statistics": "战斗统计",
            "total_battles": "总战斗次数",
            "battles_won": "胜利次数",
            "battles_lost": "失败次数",
            "win_rate": "胜率",
            "max_win_streak": "最大连胜",
            "monster_statistics": "怪物统计",
            "bosses_defeated": "击败Boss",
            "resource_statistics": "资源统计",
            "total_gold_earned": "总获得金币",
            "total_gold_spent": "总花费金币",
            "total_exp_earned": "总获得经验",
            "equipment_statistics": "装备统计",
            "equipment_found": "获得装备",
            "potion_statistics": "药剂统计",
            "potions_found": "获得药剂",
            "potions_used": "使用药剂",
            "skill_statistics": "技能统计",
            # 任务系统
            "view_quests": "查看任务",
            "quests_menu": "任务列表",
            "no_active_quests": "没有活跃任务。冒险过程中会自动生成任务。",
            "completed_quests": "已完成任务",
            "kill_monster_quest": "击杀{target}只怪物 ({current}/{target})",
            "collect_gold_quest": "收集{target}枚金币 ({current}/{target})",
            "reach_position_quest": "到达第{target}格 ({current}/{target})",
            "use_potion_quest": "使用{target}瓶药剂 ({current}/{target})",
            "quest_reward": "奖励: {gold}金币, {exp}经验值",
            "new_quest_received": "新任务已接收",
            "quest_completed": "任务完成！",
            "quest_reward_received": "获得任务奖励：{gold}金币, {exp}经验值",
            # 新地图类型
            "map_swamp": "沼泽",
            "map_snowfield": "雪原",
            "swamp_desc": "潮湿的沼泽，有毒雾和怪物",
            "snowfield_desc": "寒冷的雪原，有冰霜生物",
            # 沼泽事件
            "poison_cloud": "你误入了毒雾区，损失了",
            "quicksand": "你掉进了流沙，损失了",
            "rare_herbs": "你发现了罕见草药，恢复了",
            "swamp_merchant": "你遇到了沼泽商人！",
            "swamp_merchant_desc": "沼泽商人：'冒险者，我有特殊的商品...'",
            "poisoned": "你中毒了！接下来3回合每回合损失",
            "poison_damage": "你因中毒损失了",
            "poison_cured": "毒素已经消失",
            # 雪原事件
            "frostbite": "你遭到了冻伤，攻击力降低了",
            "avalanche": "雪崩！你损失了",
            "avalanche_loot": "但你在雪中发现了稀有装备！",
            "ice_cave": "你发现了一个冰洞，在里面休息恢复了大量血量！",
            "frost_effect": "你被冰霜效果影响，防御力降低了",
            "frostbite_effect": "冻伤效果：攻击力-10%，持续3回合",
            "frost_effect_desc": "冰霜效果：防御力-10%，持续3回合",
            # 新怪物
            "monster_crocodile": "鳄鱼",
            "monster_venom_snake": "毒蛇",
            "monster_swamp_beast": "沼泽巨兽",
            "monster_ice_wolf": "冰狼",
            "monster_snow_beast": "雪怪",
            "monster_frost_giant": "冰霜巨人",
            # Boss模板
            "boss_plains_warlord": "平原领主",
            "boss_ancient_treant": "远古树精",
            "boss_desert_sphinx": "沙漠斯芬克斯",
            "boss_demon_lord": "恶魔领主",
            "boss_mountain_dragon": "山地巨龙",
            "boss_swamp_hydra": "沼泽九头蛇",
            "boss_frost_king": "冰霜之王",
            # Boss技能
            "boss_skill_power_strike": "力量打击",
            "boss_skill_heal": "自我治疗",
            "boss_skill_root_trap": "根须陷阱",
            "boss_skill_nature_heal": "自然愈合",
            "boss_skill_sandstorm": "沙尘暴",
            "boss_skill_riddle": "谜语挑战",
            "boss_skill_fire_breath": "烈焰吐息",
            "boss_skill_summon_minions": "召唤仆从",
            "boss_skill_dragon_breath": "龙之吐息",
            "boss_skill_wing_attack": "翼击",
            "boss_skill_poison_bite": "毒噬",
            "boss_skill_regeneration": "再生",
            "boss_skill_blizzard": "暴风雪",
            "boss_skill_ice_prison": "冰之囚牢",
            # Boss战提示
            "boss_warning": "警告！前方有强大Boss！",
            "boss_enraged": "Boss进入狂暴状态，攻击力提升！",
            "boss_phase_change": "Boss进入下一阶段！",
            "boss_skill_used": "Boss使用了",
            # 状态效果系统
            "status_effects": "状态效果",
            "status_poison": "中毒",
            "status_frostbite": "冻伤",
            "status_frost": "冰霜",
            "status_duration": "剩余回合",
            "status_active": "生效中",
            "status_expired": "已结束",
            # Boss技能效果描述
            "root_trap_effect": "你的手脚被树根缠住了，下回合无法攻击！",
            "ice_prison_effect": "你被冰冻在冰牢中，下回合无法攻击！",
            "summon_minions_effect": "Boss召唤了仆从，下次攻击会更强！",
            # 新事件类型
            "event_mysterious_teleport": "神秘传送",
            "event_mysterious_teleport_desc": "你被神秘力量传送，位置发生了变化！",
            "event_sage_guidance": "贤者指引",
            "event_sage_guidance_desc": "一位神秘的贤者出现在你面前，给予了你宝贵的经验！",
            "event_robber_encounter": "遭遇强盗",
            "event_robber_encounter_desc": "一伙强盗拦住了你的去路，他们是选择战斗还是交出金币？",
            "event_mysterious_altar": "神秘祭坛",
            "event_mysterious_altar_desc": "你发现了一个神秘的祭坛，可以牺牲生命值来换取力量！",
            "event_roadside_camp": "路边营地",
            "event_roadside_camp_desc": "你发现了一个友善的营地，可以在那里休息恢复体力。",
            # 套装系统
            "equipment_set_warrior": "战士套装",
            "equipment_set_mage": "法师套装", 
            "equipment_set_assassin": "刺客套装",
            "set_bonus_warrior_glory": "战士荣耀：攻击+10，防御+5",
            "set_bonus_magic_mastery": "魔法精通：法力+30，法术强度+15%",
            "set_bonus_shadow_assault": "暗影突袭：暴击率+10%，闪避率+10%",
            "set_bonus_activated": "套装效果激活",
            # 新增的多语言文本
            "teleported_to_position": "你被传送到了第{position}格！",
            "moved_to_position": "移动到第{position}格",
            "gained_exp": "获得了 {exp} 点经验值！",
            "combat_option": "战斗",
            "pay_gold_option": "交出金币",
            "decide_to_combat": "你决定与强盗战斗！",
            "chose_combat": "选择战斗",
            "gave_gold_to_robber": "你交出了 {gold} 个金币给强盗。",
            "lost_gold": "失去了{gold}金币",
            "sacrifice_hp_for_attack": "牺牲血量换取攻击力 (+5)",
            "sacrifice_hp_for_defense": "牺牲血量换取防御力 (+3)",
            "leave_altar": "离开祭坛",
            "sacrificed_hp_for_attack_desc": "你牺牲了 {hp} 点血量，感受到了力量的涌动！",
            "sacrificed_hp_for_defense_desc": "你牺牲了 {hp} 点血量，感受到了身体的坚韧！",
            "sacrificed_hp_for_attack_event": "牺牲血量换取攻击力+5",
            "sacrificed_hp_for_defense_event": "牺牲血量换取防御力+3",
            "decide_to_leave_altar": "你决定离开祭坛，保持现状。",
            "chose_to_leave_altar": "选择离开",
            "rested_at_camp": "在营地里休息，恢复了 {heal} 点生命值！",
            "restored_hp": "恢复了{heal}点生命",
            "used_potion_event": "使用了药剂，恢复了{heal}点血量",
            # 成就系统
            "achievements": "成就",
            "achievement_unlocked": "成就已解锁",
            "total_achievements": "总成就数",
            "unlocked_achievements": "已解锁成就",
            "completion": "完成度",
            "progress_achievements": "进度成就",
            "combat_achievements": "战斗成就",
            "resource_achievements": "资源成就",
            "equipment_achievements": "装备成就",
            "skill_achievements": "技能成就",
            "special_achievements": "特殊成就",
            "back_to_menu": "返回菜单",
            "rarity": "稀有度",
            "progress": "进度"
        }
    
    def _get_english_texts(self):
        """获取英文文本"""
        return {
            "welcome_title": "Welcome to 'Heroes Invincible' Text Adventure Game",
            "welcome_desc1": "Game Instructions:",
            "welcome_desc2": "1. You will play as a hero, adventuring on a 10-grid straight map",
            "welcome_desc3": "2. Each step may trigger random events",
            "welcome_desc4": "3. Reach end to win, zero health to lose",
            "welcome_desc5": "4. Good luck, hero!",
            "continue_prompt": "Press Enter to continue...",
            "hero_creation": "Create Your Hero",
            "enter_name": "Please enter your hero name: ",
            "name_empty": "Name cannot be empty, please re-enter!",
            "game_start": "Game Start",
            "game_over": "Game Over",
            "victory": "Congratulations on Clearing!",
            "restart": "Do you want to restart game? (y/n): ",
            "yes_options": ["y", "Y", "yes"],
            "invalid_choice": "Invalid choice, please enter y or n!",
            "goodbye": "Thank you for playing 'Heroes Invincible', goodbye!",
            "hero_info": "Hero Information",
            "name": "Name",
            "hp": "Health",
            "max_hp": "Max Health",
            "attack": "Attack",
            "defense": "Defense",
            "gold": "Gold",
            "exp": "Experience",
            "level": "Level",
            "potions": "Potions",
            "position": "Position",
            "skills": "Skills",
            "map": "Map",
            "forward": "Move Forward",
            "view_status": "View Status",
            "view_history": "View Adventure History",
            "use_potion": "Use Health Potion",
            "shop": "Shop (spend gold)",
            "choose_action": "Choose your action:",
            "enter_choice": "Please enter your choice",
            "hero_victory": "You defeated",
            "monster_attack": " dealt ",
            "damage": " damage to you",
            "you_attack": "You dealt ",
            "caused_damage": " damage to ",
            "point_damage": " damage",
            "heal": "restored",
            "point_hp": "health points",
            "battle_start": "Battle begins!",
            "battle_victory": "You defeated",
            "got_exp": "You gained",
            "exp_points": "experience points and",
            "gold_coins": "gold coins",
            "level_up": "Congratulations! You reached level",
            "level": "",
            "max_hp_up": "Max HP +20, Attack +5, Defense +2",
            "newbie_village": "Newbie Village",
            "village_welcome": "Welcome to Newbie Village",
            "village_desc": "The village chief looks happy to see you and walks towards you...",
            "chief_speak": "Chief: 'Welcome, young hero! Before you embark on your adventure,",
            "chief_speak2": "       I suggest you get familiar with village first.'",
            "training_ground": "Training Ground",
            "village_shop": "Shop",
            "clinic": "Clinic",
            "chief_home": "Chief's House",
            "leave_village": "Leave Village - Start Adventure",
            "current_location": "Current location: Village Square",
            "areas": "Available areas:",
            "training_ground_desc": "Training Ground - Learn combat skills",
            "shop_desc": "Shop - Purchase basic equipment",
            "clinic_desc": "Clinic - Treat wounds",
            "chief_home_desc": "Chief's House - Get advice",
            "instructor": "Instructor: 'I'm the village combat instructor, I'll teach you some basic skills.'",
            "combat_training": "Learn combat skills (simulated battle, no danger)",
            "return_village": "Return to Village Square",
            "training_start": "Instructor: 'Great! Let's practice.'",
            "training_dummy": "A training dummy appeared...",
            "safe_battle": "This is a danger-free simulated battle!",
            "instructor_tip1": "Instructor: 'When attacking, you can choose normal attack or use skills.'",
            "instructor_tip2": "Instructor: 'Remember to reasonably use potions and healing spells to restore health.'",
            "instructor_tip3": "Instructor: 'Different skills have different effects, use them flexibly!'",
            "training_complete": "Training complete! You gained 5 experience points.",
            "shopkeeper": "Shopkeeper: 'Welcome! I have some useful items for beginners.'",
            "your_gold": "Your gold:",
            "shop_items": "Shop items:",
            "health_potion": "Health Potion",
            "beginner_weapon": "Beginner Weapon +5 Attack",
            "beginner_armor": "Beginner Armor +3 Defense",
            "leave_shop": "Leave Shop",
            "buy_potion": "You bought a health potion!",
            "buy_weapon": "You bought a beginner weapon, attack +5!",
            "buy_armor": "You bought beginner armor, defense +3!",
            "shopkeeper_goodbye": "Shopkeeper: 'Thank you for visiting, come again!'",
            "not_enough_gold": "Not enough gold or invalid choice!",
            "doctor": "Doctor: 'Oh, a new adventurer! Let me give you a check-up.'",
            "doctor_good_health": "Doctor: 'You're in good health, no treatment needed.'",
            "doctor_tip": "Doctor: 'But I still remind you, be careful during adventures!'",
            "doctor_heal": "Doctor: 'Let me help you treat...'",
            "full_heal": "After treatment, your health is fully restored!",
            "elder": "Chief: 'Ah, young hero, do you have many questions to ask?'",
            "advice_adventure": "Adventure advice",
            "advice_level": "About skills and levels",
            "advice_combat": "Combat tips",
            "leave": "Leave",
            "elder_adventure_tip": "Chief: 'Always pay attention to your health during adventures,' '       especially when facing bosses.' '       The map is full of random events,' '       some will bring you benefits, some are dangerous.'",
            "elder_level_tip": "Chief: 'Your attributes will improve with each level up,' '       and every 3 levels you have a chance to learn new skills.' '       Skills will give you an advantage in battle,' '       make good use of them!'",
            "elder_combat_tip": "Chief: 'In battle, you can choose to attack, use potions or cast spells.' '       Monster strength will increase as your level rises,' '       so don't be careless!' '       Bosses are stronger than normal monsters, but rewards are richer.'",
            "elder_goodbye": "Chief: 'Wish you a successful adventure!'",
            "elder_not_hear": "Chief: 'I didn't hear clearly what you want to know.'",
            "leave_village_msg": "Chief: 'Good luck, brave adventurer!'",
            "leave_village_msg2": "You bid farewell to villagers and embarked on adventure path...",
            "step_forward": ">>> You moved forward one step...",
            "mine_trap": "Oh no! You stepped on a mine, losing ",
            "actual_damage": " health points!",
            "dodge_mine": "You keenly detected the mine and dodged in time, taking no damage!",
            "find_bun": "Lucky! You found a magic bun, restoring ",
            "find_spring": "You found a spring of life, fully restoring all health!",
            "find_chest": "You found a treasure chest, gaining ",
            "coins": " gold coins!",
            "merchant": "You encountered a mysterious merchant!",
            "merchant_speak": "Merchant: 'Traveler, I have some good things, want to see?'",
            "no_gold": "Merchant: 'It seems you're short on money, come back next time!'",
            "learn_skill": "Learn Skill",
            "learn_skill_success": "A miracle happened! You learned",
            "mysterious_teacher": "You met a mysterious teacher! He can teach you a skill.",
            "skill_name": "] skill!",
            "skill_effect": "Effect: ",
            "find_potion": "You found a health potion!",
            "trap": "You fell into a trap, losing ",
            "dodge_trap": "You keenly detected the trap and dodged in time, taking no damage!",
            "safe_move": "Safe and sound, continue moving forward.",
            "encounter_monster": "You encountered a monster!",
            "encounter_boss": "You encountered a powerful Boss!",
            "poison": "used a health potion, restoring ",
            "use_heal": "cast a healing spell, restoring ",
            "full_hp_no_heal": "Your health is full, no need to heal!",
            "fireball": "You cast a fireball, dealing ",
            "fireball_damage": " damage to ",
            "fireball_crit": "Fireball critical! You dealt ",
            "fireball_critical": "Fireball critical! You dealt ",
            "crit": "Critical! You dealt ",
            "lifesteal": "Lifesteal effect restored ",
            "dodge": "You dodged ",
            "no_damage": "'s attack, taking no damage!",
            "boss_skill_damage": " released a powerful attack, dealing ",
            "game_over_msg": "fell on the adventure path...",
            "try_again": "Keep trying, hero!",
            "victory_msg": "successfully completed the adventure!",
            "final_status": "Final status",
            "real_hero": "You are a true hero!",
            "monsters_defeated": "Monsters defeated",
            "total_gold": "Total gold",
            "skills_learned": "Skills learned",
            "adventure_history": "Adventure History",
            "no_history": "No adventure records yet...",
            "your_journey": "Your adventure history:",
            "damage_defense": "Actual damage",
            "no_victory_heal": "Lifesteal skill kept you at an advantage in battle!",
            "victory_full_heal": "Victory fully restored all health!",
            "victory_heal": "Victory restored ",
            "boss_defeated": "defeated the powerful",
            "hero_medal": "gained [Hero Medal]!",
            "boss_lifesteal": "Lifesteal skill kept you at an advantage in boss battle!",
            "level_up_reward": "Level up reward: You learned [",
            "all_skills_learned": "You have learned all skills!",
            "fireball_desc": "Can release powerful magic attacks in battle, also triggers lifesteal",
            "lifesteal_desc": "Each attack restores 30% of damage as health",
            # New skill descriptions
            "combo_desc": "Attack twice in a row, each dealing 50% damage",
            "shield_desc": "Reduce next damage taken by 50%",
            "berserk_desc": "Increase attack by 50% and decrease defense by 50% for 3 turns",
            "focus_desc": "Next attack is guaranteed to hit and crit",
            # New skill effect descriptions
            "combo_total_damage": "Dual Strike total damage",
            "focus_critical": "Focus Critical Hit",
            "shield_activated": "Shield activated, next damage taken reduced by 50%",
            "berserk_activated": "Entered Berserk state",
            "berserk_attack_up": "Attack increased by 50%",
            "berserk_defense_down": "Defense decreased by 50%",
            "focus_activated": "Focus state activated",
            "focus_next_attack": "Next attack is guaranteed to hit and crit",
            "berserk_defense_active": "Berserk state: Defense reduced",
            "shield_reduced_damage": "Shield reduced damage to",
            "berserk_attack_active": "Berserk state: Attack increased",
            "berserk_remaining": "Berserk remaining turns",
            "berserk_turns": "turns",
            "berserk_ended": "Berserk state ended",
            "dodge_desc": "20% chance to completely avoid damage",
            "crit_desc": "15% chance to deal double damage",
            "heal_desc": "Can restore 25-40 health in battle",
            "unknown_effect": "Unknown effect",
            "choose_language": "Please select language",
            "chinese": "中文",
            "english": "English",
            "unit_coins": "",
            "unit_monsters": "",
            "unit_skills": "",
            "block_separator": "="*50,
            "item_separator": ": ",
            "round": "Round",
            "normal_attack": "Normal Attack",
            "remaining": "Remaining",
            "cast_fireball": "Cast Fireball",
            "locked": "Locked",
            "cast_healing": "Cast Healing",
            # New skill actions
            "cast_combo": "Use Dual Strike",
            "cast_shield": "Use Shield",
            "cast_berserk": "Enter Berserk",
            "cast_focus": "Focus",
            "invalid_action": "Cannot perform this action, changed to normal attack!",
            "your_hp": "Your health ",
            "monster_hp": "Monster health ",
            "boss_hp": "Boss health ",
            "boss_powerful_attack": " used a powerful attack, dealing ",
            "restore": "Restore",
            "permanent": "Permanent",
            "strength_potion": "Strength Potion",
            "defense_scroll": "Defense Scroll",
            "special_price": "Shop special price",
            "no_potions": "You have no potions!",
            "already_at_end": "You've already reached the end!",
            "danger_encounter": "Danger! Encountered the powerful",
            "boss_battle_start": "Boss battle begins!",
            "boss_victory": "You defeated the powerful",
            "hero_badge": "Got [Hero Badge]!",
            "defeat_boss": "Defeated Boss",
            "lifesteal_advantage": "Lifesteal skill kept you at an advantage in boss battle!",
            "dodge_attack": "You dodged",
            "dodge_success": "'s attack, taking no damage!",
            "healing_spell": "You cast a healing spell, restoring ",
            # 装备系统
            "weapon": "Weapon",
            "armor": "Armor",
            "accessory": "Accessory",
            "none": "None",
            "inventory": "Inventory",
            "inventory_empty": "Your inventory is empty!",
            "equipment_management": "Equipment Management",
            "current_weapon": "Current Weapon",
            "current_armor": "Current Armor",
            "current_accessory": "Current Accessory",
            "current_equipment": "Current Equipment",
            "view_inventory": "View Inventory",
            "equip_item": "Equip Item",
            "unequip_item": "Unequip Item",
            "unequip_weapon": "Unequip Weapon",
            "unequip_armor": "Unequip Armor",
            "unequip_accessory": "Unequip Accessory",
            "return_game": "Return to Game",
            "select_item_to_equip": "Select item number to equip",
            "invalid_item": "Invalid item number!",
            "invalid_item_type": "Invalid equipment type!",
            "no_equipped_item": "No equipment in this slot!",
            "equip_success": "Successfully equipped",
            "unequip_success": "Successfully unequipped",
            "equipment_shop": "Equipment Shop",
            "select_category": "Select product category",
            "weapons": "Weapons",
            "armors": "Armors",
            "accessories": "Accessories",
            "buy": "Buy",
            "back": "Back",
            "buy_success": "Successfully bought",
            "mysterious_merchant": "You encountered a mysterious merchant!",
            "treasure_chest_with_equipment": "You found a shining treasure chest!",
            # 难度和地图系统
            "select_map_difficulty": "Select Map and Difficulty",
            "select_difficulty": "Select Difficulty",
            "difficulty_easy": "Easy",
            "difficulty_normal": "Normal",
            "difficulty_hard": "Hard",
            "difficulty_nightmare": "Nightmare",
            "select_map_type": "Select Map Type",
            "select_map_type": "Select your adventure map type",
            "map_plains": "Plains",
            "map_forest": "Forest",
            "map_desert": "Desert",
            "map_dungeon": "Dungeon",
            "map_mountain": "Mountain",
            "plains_desc": "Flat grasslands, suitable for beginners",
            "forest_desc": "Mysterious forest with many herbs and beasts",
            "desert_desc": "Hot desert with dangerous creatures",
            "dungeon_desc": "Gloomy dungeon with powerful enemies",
            "mountain_desc": "Steep mountains with giants and dragons",
            "difficulty": "Difficulty",
            "map_type": "Map Type",
            "map_length": "Map Length",
            "game_settings": "Game Settings",
            # 新事件文本
            "thorns_damage": "You were scratched by thorns, losing",
            "find_herbs": "You found healing herbs, restoring",
            "dehydration": "You felt severely dehydrated, losing",
            "find_oasis": "You found a desert oasis, restoring",
            "dungeon_trap": "You triggered a dungeon trap, losing",
            "encounter_ghost": "You encountered",
            "mountain_hazard": "You encountered an avalanche/falling rocks, losing",
            "find_gem": "You found gems, gaining",
            "ghost_drop_equipment": "The ghost dropped equipment when dissipating!",
            "ghost_dissipate": "The ghost dissipates into the void...",
            "encounter_ghost": "You encountered a ghost!",
            # Newbie village additional texts
            "village_clinic": "Clinic",
            "elder_advice_short": "Elder's Advice",
            "start_adventure": "Start Adventure",
            "hp_recovered": "Your health has been fully restored!",
            "training_desc": "The training ground allows you to practice combat skills and gain experience.",
            "practice_combat": "Practice Combat",
            "learn_skill_short": "Learn Skill",
            # Skill names
            "fireball_skill": "Fireball",
            "healing_skill": "Healing",
            "critical_skill": "Critical",
            "lifesteal_skill": "Lifesteal",
            "dodge_skill": "Dodge",
            # New skills
            "combo_skill": "Dual Strike",
            "shield_skill": "Shield",
            "berserk_skill": "Berserk",
            "focus_skill": "Focus",
            "critical_hit": "Critical hit! You dealt ",
            "lifesteal_effect": "Lifesteal restored ",
            # Rarity names
            "rarity_common": "Common",
            "rarity_uncommon": "Uncommon",
            "rarity_rare": "Rare",
            "rarity_epic": "Epic",
            "rarity_legendary": "Legendary",
            "return_to_village": "Return to Village",
            "practice_start": "Practice begins! Your opponent is",
            "practice_victory": "Practice complete! You defeated",
            "practice_reward": "Gained 20 experience and 10 gold!",
            "learn_skill_cost": "Learning a skill costs",
            "trainer_introduction": "The trainer says: I can teach you some useful skills.",
            "confirm_learn": "Confirm learning? (y/n)",
            "cancel_learn": "You cancelled learning.",
            "shopkeeper_greeting": "Shopkeeper: 'Welcome to my shop! What would you like to buy?'",
            "how_many": "Quantity",
            "exit_shop": "Exit Shop",
            "use_potion_short": "Use Potion",
            "healing_spell_short": "Healing Spell",
            "merchant_desc": "Merchant: 'Traveler, I have many fine goods, want to take a look?'",
            "buy_equipment": "Buy Equipment",
            "buy_equipment_short": "Buy Equipment",
            "leave_merchant": "Leave",
            "merchant_encounter": "Meet Merchant",
            "mysterious_merchant_encounter": "Mysterious Merchant",
            "mysterious_merchant_desc": "Mysterious Merchant: 'Brave adventurer, I have rare equipment for sale...'",
            "empty_inventory": "Inventory is empty",
            "enter_item_number": "Enter item number",
            "return_to_game": "Return to Game",
            "treasure_chest": "Treasure Chest",
            "treasure_chest_desc": "You found a mysterious chest, which might contain precious equipment!",
            "no_events_yet": "No adventure records yet...",
            "clinic_offer": "Doctor: 'I can heal you, restoring",
            "clinic_cost": "Treatment cost",
            "confirm_treatment": "Confirm treatment? (y/n)",
            "cancel_treatment": "You cancelled treatment.",
            "hp_full": "Doctor: 'You are in good health, no treatment needed.'",
            "treatment_success": "After treatment, your health is fully restored!",
            "elder_advice_title": "Elder's Advice",
            "elder_desc": "Elder: 'Young hero, let me give you some advice.'",
            "restart_prompt": "Do you want to restart the game",
            # Training dummy name
            "training_dummy": "Training Dummy",
            # Elder advice
            "elder_advice_1": "Remember, potions are lifesavers, don't hesitate to use them!",
            "elder_advice_2": "Choose skills carefully when leveling up, different skills suit different combat styles.",
            "elder_advice_3": "Higher difficulty maps have stronger enemies, but also better rewards.",
            "elder_advice_4": "Different maps have different dangers and opportunities, choose what suits you.",
            "elder_advice_5": "Equipment can greatly boost your combat power, collect best gear you can!",
            "elder_advice_6": "Bosses use powerful attacks every 3 rounds, keep your health up!",
            # Monster names
            "monster_goblin": "Goblin",
            "monster_skeleton": "Skeleton",
            "monster_wolf": "Wolf",
            "monster_bandit": "Bandit",
            "monster_slime": "Slime",
            "monster_pixie": "Pixie",
            "monster_orc_warrior": "Orc Warrior",
            "monster_bandit_leader": "Bandit Leader",
            "monster_dark_mage": "Dark Mage",
            "monster_elite_assassin": "Elite Assassin",
            "monster_troll": "Troll",
            "monster_beast": "Beast",
            "monster_spider": "Spider",
            "monster_scorpion": "Scorpion",
            "monster_sand_worm": "Sand Worm",
            "monster_golem": "Golem",
            "monster_ghost": "Ghost",
            "monster_demon": "Demon",
            "monster_giant": "Giant",
            "monster_dragon": "Dragon",
            "monster_titan": "Titan",
            # Boss names
            "boss_lesser_demon_leader": "Lesser Demon Leader",
            "boss_cave_troll": "Cave Troll",
            "boss_shadow_spider": "Shadow Spider",
            "boss_dark_lord": "Dark Lord",
            "boss_frost_queen": "Frost Queen",
            "boss_fire_lizard": "Fire Lizard",
            "boss_ancient_dragon": "Ancient Dragon",
            "boss_abyss_demon": "Abyss Demon",
            "boss_death_knight": "Death Knight",
            "boss_chaos_wizard": "Chaos Wizard",
            # Ghost names
            "ghost_wandering": "Wandering Ghost",
            "ghost_vengeful": "Vengeful Spirit",
            "ghost_soul_guardian": "Soul Guardian",
            # Game messages
            "ghost_no_exp_warning": "Warning: Defeating ghosts grants no experience!",
            "ghost_dissipate_nothing": "The ghost dissipated, leaving nothing...",
            "ghost_leave_equipment": "The ghost left a mysterious item!",
            "victory_full_restore": "Victory completely restored all health!",
            # Skill names
            "lifesteal_skill_name": "Lifesteal",
            # Equipment messages
            "no_equipment_in_slot": "No equipment in that slot!",
            "found_equipment": "You found: ",
            "equipment_stats": "Stats: ",
            "used_potion_event": "Used potion, restored ",
            "hp_points_event": " HP",
            "learned_skill_event": "Learned skill: ",
            "found_equipment_event": "Found ",
            "defeat_boss_event": "Defeated boss",
            "got_gold_from_ghost": "Got ",
            "got_gold_from_ghost_en": "Got ",
            "skill_bracket_zh": "【",
            "skill_bracket_zh_end": "】",
            "skill_bracket_en": "[",
            "skill_bracket_en_end": "]",
            # Save System
            "main_menu": "Main Menu",
            "new_game": "New Game",
            "load_game": "Load Game",
            "exit_game": "Exit Game",
            "save_game": "Save Game",
            "save_and_exit": "Save and Exit",
            "save_success": "Game saved to slot",
            "save_failed": "Save failed",
            "load_success": "Save loaded",
            "load_failed": "Failed to load save",
            "no_save_slot": "No save in this slot",
            "save_slot_title": "Select Save Slot",
            "save_slot_empty": "Slot",
            "save_slot_info": "Hero",
            "save_slot_level": "Level",
            "save_slot_map": "Map",
            "save_slot_difficulty": "Difficulty",
            "save_slot_position": "Progress",
            "save_slot_time": "Save Time",
            "delete_save": "Delete Save",
            "delete_confirm": "Confirm delete this save? (y/n)",
            "delete_success": "Save deleted",
            "save_corrupted": "Save file corrupted",
            "select_slot_to_load": "Select save slot to load",
            "select_slot_to_save": "Select slot to save",
            "return_to_main": "Return to Main Menu",
            "current_save": "Current Save",
            "overwrite_save": "Overwrite existing save",
            "empty_slot": "Empty Slot",
            # Statistics System
            "view_statistics": "View Statistics",
            "play_time": "Play Time",
            "total_steps": "Total Steps",
            "battle_statistics": "Battle Statistics",
            # New map types
            "map_swamp": "Swamp",
            "map_snowfield": "Snowfield",
            "swamp_desc": "Damp swamp with poisonous fog and monsters",
            "snowfield_desc": "Cold snowfield with frost creatures",
            # Swamp events
            "poison_cloud": "You wandered into a poison cloud area, losing",
            "quicksand": "You fell into quicksand, losing",
            "rare_herbs": "You found rare herbs, restoring",
            "swamp_merchant": "You encountered a swamp merchant!",
            "swamp_merchant_desc": "Swamp Merchant: 'Adventurer, I have special goods...'",
            "poisoned": "You are poisoned! You will lose",
            "poison_damage": "You lost",
            "poison_cured": "The poison has worn off",
            # Snowfield events
            "frostbite": "You suffered from frostbite, your attack power reduced by",
            "avalanche": "Avalanche! You lost",
            "avalanche_loot": "But you found rare equipment in the snow!",
            "ice_cave": "You found an ice cave, resting inside restored a lot of health!",
            "frost_effect": "You are affected by frost effect, defense reduced",
            "frostbite_effect": "Frostbite effect: Attack -10%, lasts 3 rounds",
            "frost_effect_desc": "Frost effect: Defense -10%, lasts 3 rounds",
            # New monsters
            "monster_crocodile": "Crocodile",
            "monster_venom_snake": "Venom Snake",
            "monster_swamp_beast": "Swamp Beast",
            "monster_ice_wolf": "Ice Wolf",
            "monster_snow_beast": "Snow Beast",
            "monster_frost_giant": "Frost Giant",
            # Boss templates
            "boss_plains_warlord": "Plains Warlord",
            "boss_ancient_treant": "Ancient Treant",
            "boss_desert_sphinx": "Desert Sphinx",
            "boss_demon_lord": "Demon Lord",
            "boss_mountain_dragon": "Mountain Dragon",
            "boss_swamp_hydra": "Swamp Hydra",
            "boss_frost_king": "Frost King",
            # Boss skills
            "boss_skill_power_strike": "Power Strike",
            "boss_skill_heal": "Self Heal",
            "boss_skill_root_trap": "Root Trap",
            "boss_skill_nature_heal": "Nature Heal",
            "boss_skill_sandstorm": "Sandstorm",
            "boss_skill_riddle": "Riddle Challenge",
            "boss_skill_fire_breath": "Fire Breath",
            "boss_skill_summon_minions": "Summon Minions",
            "boss_skill_dragon_breath": "Dragon Breath",
            "boss_skill_wing_attack": "Wing Attack",
            "boss_skill_poison_bite": "Poison Bite",
            "boss_skill_regeneration": "Regeneration",
            "boss_skill_blizzard": "Blizzard",
            "boss_skill_ice_prison": "Ice Prison",
            # Boss battle tips
            "boss_warning": "Warning! Powerful Boss ahead!",
            "boss_enraged": "Boss enters enraged state, attack increased!",
            "boss_phase_change": "Boss enters next phase!",
            "boss_skill_used": "Boss used",
            # Status effect system
            "status_effects": "Status Effects",
            "status_poison": "Poisoned",
            "status_frostbite": "Frostbitten",
            "status_frost": "Frosted",
            "status_duration": "Rounds remaining",
            "status_active": "Active",
            "status_expired": "Expired",
            # Boss skill effect descriptions
            "root_trap_effect": "Your hands and feet are entangled by roots, you cannot attack next round!",
            "ice_prison_effect": "You are frozen in an ice prison, you cannot attack next round!",
            "summon_minions_effect": "Boss summoned minions, next attack will be stronger!",
            # New event types
            "event_mysterious_teleport": "Mysterious Teleport",
            "event_mysterious_teleport_desc": "You were teleported by a mysterious force, your position has changed!",
            "event_sage_guidance": "Sage Guidance",
            "event_sage_guidance_desc": "A mysterious sage appeared before you and gave you valuable experience!",
            "event_robber_encounter": "Robber Encounter",
            "event_robber_encounter_desc": "A group of robbers blocked your path, will you fight or give up your gold?",
            "event_mysterious_altar": "Mysterious Altar",
            "event_mysterious_altar_desc": "You found a mysterious altar where you can sacrifice health for power!",
            "event_roadside_camp": "Roadside Camp",
            "event_roadside_camp_desc": "You found a friendly camp where you can rest and recover your strength.",
            # Set System
            "equipment_set_warrior": "Warrior Set",
            "equipment_set_mage": "Mage Set", 
            "equipment_set_assassin": "Assassin Set",
            "set_bonus_warrior_glory": "Warrior Glory: Attack +10, Defense +5",
            "set_bonus_magic_mastery": "Magic Mastery: Mana +30, Spell Power +15%",
            "set_bonus_shadow_assault": "Shadow Assault: Critical +10%, Dodge +10%",
            "set_bonus_activated": "Set Bonus Activated",
            # New multilingual text
            "teleported_to_position": "You were teleported to position {position}!",
            "moved_to_position": "Moved to position {position}",
            "gained_exp": "You gained {exp} experience points!",
            "combat_option": "Combat",
            "pay_gold_option": "Give Gold",
            "decide_to_combat": "You decided to fight the robbers!",
            "chose_combat": "Chose combat",
            "gave_gold_to_robber": "You gave {gold} gold coins to the robbers.",
            "lost_gold": "Lost {gold} gold",
            "sacrifice_hp_for_attack": "Sacrifice HP for Attack (+5)",
            "sacrifice_hp_for_defense": "Sacrifice HP for Defense (+3)",
            "leave_altar": "Leave Altar",
            "sacrificed_hp_for_attack_desc": "You sacrificed {hp} health points and felt a surge of power!",
            "sacrificed_hp_for_defense_desc": "You sacrificed {hp} health points and felt your body become tougher!",
            "sacrificed_hp_for_attack_event": "Sacrificed HP for attack+5",
            "sacrificed_hp_for_defense_event": "Sacrificed HP for defense+3",
            "decide_to_leave_altar": "You decided to leave the altar, keeping things as they are.",
            "chose_to_leave_altar": "Chose to leave",
            "rested_at_camp": "You rested at the camp and restored {heal} health points!",
            "restored_hp": "Restored {heal} HP",
            "used_potion_event": "Used potion, restored {heal} HP",
            # Achievement System
            "achievements": "Achievements",
            "achievement_unlocked": "Achievement Unlocked",
            "total_achievements": "Total Achievements",
            "unlocked_achievements": "Unlocked Achievements",
            "completion": "Completion",
            "progress_achievements": "Progress Achievements",
            "combat_achievements": "Combat Achievements",
            "resource_achievements": "Resource Achievements",
            "equipment_achievements": "Equipment Achievements",
            "skill_achievements": "Skill Achievements",
            "special_achievements": "Special Achievements",
            "back_to_menu": "Back to Menu",
            "rarity": "Rarity",
            "progress": "Progress",
            "total_battles": "Total Battles",
            "battles_won": "Battles Won",
            "battles_lost": "Battles Lost",
            "win_rate": "Win Rate",
            "max_win_streak": "Max Win Streak",
            "monster_statistics": "Monster Statistics",
            "bosses_defeated": "Bosses Defeated",
            "resource_statistics": "Resource Statistics",
            "total_gold_earned": "Total Gold Earned",
            "total_gold_spent": "Total Gold Spent",
            "total_exp_earned": "Total Exp Earned",
            "equipment_statistics": "Equipment Statistics",
            "equipment_found": "Equipment Found",
            "potion_statistics": "Potion Statistics",
            "potions_found": "Potions Found",
            "potions_used": "Potions Used",
            "skill_statistics": "Skill Statistics",
            # Quest System
            "view_quests": "View Quests",
            "quests_menu": "Quest List",
            "no_active_quests": "No active quests. Quests will be automatically generated during your adventure.",
            "completed_quests": "Completed Quests",
            "kill_monster_quest": "Defeat {target} monsters ({current}/{target})",
            "collect_gold_quest": "Collect {target} gold coins ({current}/{target})",
            "reach_position_quest": "Reach position {target} ({current}/{target})",
            "use_potion_quest": "Use {target} potions ({current}/{target})",
            "quest_reward": "Reward: {gold} gold, {exp} exp",
            "new_quest_received": "New quest received",
            "quest_completed": "Quest completed!",
            "quest_reward_received": "Received quest reward: {gold} gold, {exp} exp"
        }
    
    def get_text(self, key, **kwargs):
        """获取指定键的文本，支持参数替换"""
        text = self.texts.get(key, key)
        if kwargs:
            try:
                return text.format(**kwargs)
            except (KeyError, ValueError):
                return text
        return text
    
    # 格式化函数集合
    def _get_position_format(self, position, total):
        """获取位置格式化的文本"""
        if self.language == "zh":
            return f"第{position}格 / 共{total}格"
        else:
            return f"{position} / {total}"
    
    def _get_hero_marker(self):
        """获取英雄标记"""
        return "英雄" if self.language == "zh" else "Hero"
    
    def _get_event_text(self, event_key, value=None):
        """获取事件文本"""
        if self.language == "zh":
            return self.texts.get(event_key, event_key) + (str(value) if value is not None else "")
        else:
            # 英文事件文本的特定格式
            event_map = {
                "mine_trap": f"Stepped on mine, lost {value} HP",
                "find_bun": f"Found magic bun, restored {value} HP",
                "find_chest": f"Found treasure chest, gained {value} gold",
                "find_potion": "Found health potion",
                "safe_move": "Safe move, nothing happened",
                "thorns_damage": f"Scratched by thorns, lost {value} HP",
                "find_herbs": f"Found healing herbs, restored {value} HP",
                "dehydration": f"Felt dehydrated, lost {value} HP",
                "find_oasis": f"Found desert oasis, restored {value} HP",
                "got_gold_from_ghost": f"Got {value} gold from the ghost",
                "dungeon_trap": f"Triggered dungeon trap, lost {value} HP",
                "mountain_hazard": f"Encountered avalanche/rockfall, lost {value} HP",
                "find_gem": f"Found gems, gained {value} gold"
            }
            return event_map.get(event_key, self.texts.get(event_key, event_key))
    
    def _get_skill_brackets(self):
        """获取技能括号"""
        if self.language == "zh":
            return (self.texts.get('skill_bracket_zh', '【'), 
                   self.texts.get('skill_bracket_zh_end', '】'))
        else:
            return (self.texts.get('skill_bracket_en', '['), 
                   self.texts.get('skill_bracket_en_end', ']'))
    
    def _get_equipment_name(self, equipment_db, item_type, rarity):
        """获取装备名称"""
        names = equipment_db[item_type][self.language][rarity]
        import random
        return random.choice(names)
    
    # 调用格式化函数的统一接口
    def format_text(self, format_type, *args, **kwargs):
        """格式化文本的统一接口"""
        if format_type in self.format_functions:
            return self.format_functions[format_type](*args, **kwargs)
        return None