#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
英雄无敌 - 多语言支持模块
"""

# 语言支持类
class LanguageSupport:
    """游戏多语言支持"""
    
    def __init__(self, language="zh"):
        self.language = language
        self.set_language(language)
    
    def set_language(self, language):
        """设置当前语言"""
        self.language = language
        if language == "en":
            self.texts = self._get_english_texts()
        else:
            self.texts = self._get_chinese_texts()
    
    def _get_chinese_texts(self):
        """获取中文文本"""
        return {
            "welcome_title": "欢迎来到《英雄无敌》文字冒险游戏",
            "welcome_desc1": "游戏说明：",
            "welcome_desc2": "1. 你将扮演一位英雄，在10格直线地图上冒险",
            "welcome_desc3": "2. 每一步都可能遇到随机事件",
            "welcome_desc4": "3. 到达终点即为胜利，血量归零即为失败",
            "welcome_desc5": "4. 祝你好运，英雄！",
            "continue_prompt": "按回车键继续...",
            "hero_creation": "创建你的英雄",
            "enter_name": "请输入你的英雄名字: ",
            "name_empty": "名字不能为空，请重新输入！",
            "game_start": "游戏开始",
            "game_over": "游戏结束",
            "victory": "恭喜通关！",
            "restart": "是否重新开始游戏？(y/n): ",
            "invalid_choice": "无效选择，请输入 y 或 n！",
            "goodbye": "感谢游玩《英雄无敌》，再见！",
            "hero_info": "英雄信息",
            "name": "名字",
            "hp": "血量",
            "max_hp": "最大血量",
            "attack": "攻击力",
            "defense": "防御力",
            "gold": "金币",
            "exp": "经验值",
            "level": "等级",
            "potions": "药剂",
            "position": "位置",
            "skills": "技能",
            "map": "地图",
            "forward": "向前移动",
            "view_status": "查看状态",
            "view_history": "查看冒险历程",
            "use_potion": "使用生命药剂",
            "shop": "商店 (消耗金币)",
            "choose_action": "选择你的行动:",
            "enter_choice": "请输入选择",
            "hero_victory": "你击败了",
            "monster_attack": "对你造成了",
            "damage": "点伤害",
            "you_attack": "你对",
            "caused_damage": "造成了",
            "point_damage": "点伤害",
            "heal": "恢复了",
            "point_hp": "点血量",
            "battle_start": "战斗开始！",
            "battle_victory": "你击败了",
            "got_exp": "获得了",
            "exp_points": "经验值和",
            "gold_coins": "金币",
            "level_up": "恭喜！你升到了",
            "level": "级",
            "max_hp_up": "血量上限+20, 攻击力+5, 防御力+2",
            "newbie_village": "新手村",
            "village_welcome": "欢迎来到新手村",
            "village_desc": "村长看起来很高兴见到你，并向你走来...",
            "chief_speak": "村长：'欢迎，年轻的英雄！在你踏上冒险之旅前，",
            "chief_speak2": "       我建议你先在村里熟悉一下。'",
            "training_ground": "训练场",
            "village_shop": "商店",
            "clinic": "诊所",
            "chief_home": "村长家",
            "leave_village": "离开村庄 - 开始冒险",
            "current_location": "当前位置：村庄广场",
            "areas": "可行动区域：",
            "training_ground_desc": "训练场 - 学习战斗技巧",
            "shop_desc": "商店 - 购买基础装备",
            "clinic_desc": "诊所 - 治疗伤口",
            "chief_home_desc": "村长家 - 获得建议",
            "instructor": "教官：'我是村里的格斗教官，我来教你一些基础技巧。'",
            "combat_training": "学习战斗技巧（模拟战斗，无危险）",
            "return_village": "返回村庄广场",
            "training_start": "教官：'很好！让我们来练习一下。'",
            "training_dummy": "出现了一个训练假人...",
            "safe_battle": "这是一场无危险的模拟战斗！",
            "instructor_tip1": "教官：'攻击时可以选择普通攻击或使用技能。'",
            "instructor_tip2": "教官：'记得合理使用药剂和治疗术恢复生命值。'",
            "instructor_tip3": "教官：'不同的技能有不同的效果，要灵活运用！'",
            "training_complete": "训练完成！你获得了5点经验值。",
            "shopkeeper": "店主：'欢迎光临！我这里有一些对新手有用的物品。'",
            "your_gold": "你的金币:",
            "shop_items": "商店商品：",
            "health_potion": "生命药剂",
            "beginner_weapon": "新手武器 +5攻击力",
            "beginner_armor": "新手护甲 +3防御力",
            "leave_shop": "离开商店",
            "buy_potion": "你购买了一瓶生命药剂！",
            "buy_weapon": "你购买了新手武器，攻击力+5！",
            "buy_armor": "你购买了新手护甲，防御力+3！",
            "shopkeeper_goodbye": "店主：'感谢光临，下次再来！'",
            "not_enough_gold": "金币不足或无效选择！",
            "doctor": "医生：'哦，一位新的冒险者！让我给你做个检查。'",
            "doctor_good_health": "医生：'你的身体状况很好，不需要治疗。'",
            "doctor_tip": "医生：'但还是要提醒你，冒险时注意安全！'",
            "doctor_heal": "医生：'让我帮你治疗一下...'",
            "full_heal": "治疗后，你的血量完全恢复了！",
            "elder": "村长：'啊，年轻的英雄，你有很多问题想问吗？'",
            "advice_adventure": "关于冒险的建议",
            "advice_level": "关于技能和等级",
            "advice_combat": "关于战斗技巧",
            "leave": "离开",
            "elder_adventure_tip": "村长：'冒险时要时刻注意你的血量，' '       尤其是遇到Boss时更要谨慎。' '       地图上充满了各种随机事件，' '       有些会给你带来好处，有些则很危险。'",
            "elder_level_tip": "村长：'每次升级你的属性都会提升，' '       每3级你还有机会学会新技能。' '       技能会让你在战斗中更有优势，' '       好好利用它们！'",
            "elder_combat_tip": "村长：'战斗中你可以选择攻击、使用药剂或释放技能。' '       怪物的强度会随着你的等级提高而增强，' '       所以不要掉以轻心！' '       Boss比普通怪物更强大，但奖励也更丰厚。'",
            "elder_goodbye": "村长：'祝你冒险顺利！'",
            "elder_not_hear": "村长：'我没听清楚你想了解什么。'",
            "leave_village_msg": "村长：'祝你好运，勇敢的冒险者！'",
            "leave_village_msg2": "你告别了村民，踏上了冒险之路...",
            "step_forward": ">>> 你向前走了一步...",
            "mine_trap": "糟糕！你踩到了地雷，损失了",
            "actual_damage": "点血量！",
            "dodge_mine": "你敏锐地察觉到了地雷，及时闪避，没有受到伤害！",
            "find_bun": "幸运！你发现了一个魔法包子，恢复了",
            "find_spring": "你发现了一处生命之泉，完全恢复了所有血量！",
            "find_chest": "你发现了一个宝箱，获得了",
            "coins": "枚金币！",
            "merchant": "你遇到了一位神秘的商人！",
            "merchant_speak": "商人: '旅行者，我有一些好东西，要看看吗？'",
            "no_gold": "商人: '看来你囊中羞涩，下次再来吧！'",
            "learn_skill": "学习技能",
            "learn_skill_success": "奇迹发生！你学会了",
            "skill_name": "】技能！",
            "skill_effect": "效果: ",
            "find_potion": "你发现了一瓶生命药剂！",
            "trap": "你掉入了陷阱，损失了",
            "dodge_trap": "你敏锐地察觉到了陷阱，及时闪避，没有受到伤害！",
            "safe_move": "平安无事，继续前进。",
            "encounter_monster": "你遇到了一只怪物！",
            "encounter_boss": "你遇到了一只强大的Boss！",
            "poison": "使用了生命药剂，恢复了",
            "use_heal": "释放了治疗术，恢复了",
            "full_hp_no_heal": "你的血量已满，不需要治疗！",
            "fireball": "你释放了火球术，对",
            "fireball_damage": "造成了",
            "fireball_crit": "火球术暴击！你对",
            "crit": "暴击！你对",
            "lifesteal": "吸血效果恢复了",
            "dodge": "你闪避了",
            "no_damage": "的攻击，没有受到伤害！",
            "boss_skill_damage": "释放了强力攻击，对你造成了",
            "game_over_msg": "倒在了冒险途中...",
            "try_again": "再接再厉，英雄！",
            "victory_msg": "成功完成了冒险！",
            "final_status": "最终状态",
            "real_hero": "你是一位真正的英雄！",
            "monsters_defeated": "击败怪物",
            "total_gold": "获得金币",
            "skills_learned": "已学技能",
            "adventure_history": "冒险历程",
            "no_history": "还没有任何冒险记录...",
            "your_journey": "你的冒险历程:",
            "damage_defense": "实际伤害",
            "no_victory_heal": "吸血技能让你在战斗中保持了优势！",
            "victory_full_heal": "胜利完全恢复了所有血量！",
            "victory_heal": "胜利恢复了",
            "boss_defeated": "击败了强大的",
            "hero_medal": "获得了【英雄徽章】！",
            "boss_lifesteal": "吸血技能让你在Boss战中保持了优势！",
            "level_up_reward": "升级奖励：你学会了",
            "all_skills_learned": "你已经学会了所有技能！",
            "fireball_desc": "战斗中可以释放强力魔法攻击，也能触发吸血",
            "lifesteal_desc": "每次攻击都会回复伤害值30%的血量",
            "dodge_desc": "20%概率完全避免伤害",
            "crit_desc": "15%概率造成双倍伤害",
            "heal_desc": "战斗中可以恢复25-40点血量",
            "unknown_effect": "未知效果",
            "choose_language": "请选择语言/Please select language",
            "chinese": "中文",
            "english": "English",
            "unit_coins": "枚",
            "unit_monsters": "只",
            "unit_skills": "个",
            "block_separator": "="*50,
            "item_separator": ": ",
            "round": "第",
            "normal_attack": "普通攻击",
            "remaining": "剩余",
            "cast_fireball": "释放火球术",
            "locked": "未解锁",
            "cast_healing": "释放治疗术",
            "invalid_action": "无法执行该操作，改为普通攻击！",
            "your_hp": "你的血量",
            "monster_hp": "怪物血量",
            "boss_hp": "Boss血量",
            "restore": "恢复",
            "permanent": "永久",
            "strength_potion": "力量药水",
            "defense_scroll": "防御卷轴",
            "special_price": "商店特惠价",
            "no_potions": "你没有药剂了！",
            "already_at_end": "你已经到达终点了！",
            "danger_encounter": "危险！遭遇了强大的",
            "boss_battle_start": "Boss战开始！",
            "boss_victory": "你击败了强大的",
            "hero_badge": "获得了【英雄徽章】！",
            "defeat_boss": "击败Boss",
            "lifesteal_advantage": "吸血技能让你在Boss战中保持了优势！",
            "dodge_attack": "你闪避了",
            "dodge_success": "的攻击，没有受到伤害！",
            "healing_spell": "你释放了治疗术，恢复了",
            # 装备系统
            "weapon": "武器",
            "armor": "防具",
            "accessory": "饰品",
            "none": "无",
            "inventory": "背包",
            "inventory_empty": "你的背包是空的！",
            "equipment_management": "装备管理",
            "current_weapon": "当前武器",
            "current_armor": "当前防具",
            "current_accessory": "当前饰品",
            "current_equipment": "当前装备",
            "view_inventory": "查看背包",
            "equip_item": "装备物品",
            "unequip_item": "卸下装备",
            "unequip_weapon": "卸下武器",
            "unequip_armor": "卸下防具",
            "unequip_accessory": "卸下饰品",
            "return_game": "返回游戏",
            "select_item_to_equip": "选择要装备的物品编号",
            "invalid_item": "无效的物品编号！",
            "invalid_item_type": "无效的装备类型！",
            "no_equipped_item": "该栏位没有装备！",
            "equip_success": "成功装备",
            "unequip_success": "成功卸下",
            "equipment_shop": "装备商店",
            "select_category": "选择商品类别",
            "weapons": "武器",
            "armors": "防具",
            "accessories": "饰品",
            "buy": "购买",
            "back": "返回",
            "buy_success": "成功购买",
            "mysterious_merchant": "你遇到了一位神秘的商人！",
            "treasure_chest_with_equipment": "你发现了一个闪亮的宝箱！",
            # 难度和地图系统
            "select_map_difficulty": "选择地图和难度",
            "select_difficulty": "选择难度",
            "difficulty_easy": "简单",
            "difficulty_normal": "普通",
            "difficulty_hard": "困难",
            "difficulty_nightmare": "噩梦",
            "select_map_type": "选择地图类型",
            "select_map_type": "选择你冒险的地图类型",
            "map_plains": "平原",
            "map_forest": "森林",
            "map_desert": "沙漠",
            "map_dungeon": "地牢",
            "map_mountain": "山脉",
            "plains_desc": "平坦的草原，适合新手",
            "forest_desc": "神秘的森林，有很多草药和野兽",
            "desert_desc": "炎热的沙漠，有危险的生物",
            "dungeon_desc": "阴森的地牢，强大的敌人",
            "mountain_desc": "险峻的山脉，有巨人和龙",
            "difficulty": "难度",
            "map_type": "地图类型",
            "map_length": "地图长度",
            "game_settings": "游戏设置",
            # 新事件文本
            "thorns_damage": "你被荆棘刺伤，损失了",
            "find_herbs": "你发现了治愈草药，恢复了",
            "dehydration": "你感到极度脱水，损失了",
            "find_oasis": "你发现了沙漠绿洲，恢复了",
            "dungeon_trap": "你触发了地牢陷阱，损失了",
            "encounter_ghost": "你遇到了",
            "mountain_hazard": "你遭遇了雪崩/落石，损失了",
            "find_gem": "你发现了宝石，获得了",
            "ghost_drop_equipment": "鬼魂消散时掉落了装备！",
            "ghost_dissipate": "鬼魂消散在虚空中...",
            "encounter_ghost": "你遇到了一只鬼魂！",
            # 新手村额外文本
            "village_clinic": "诊所",
            "elder_advice_short": "长老建议",
            "start_adventure": "开始冒险",
            "hp_recovered": "你的血量已完全恢复！",
            "training_desc": "训练场可以让你练习战斗技巧，提升经验值。",
            "practice_combat": "练习战斗",
            "learn_skill_short": "学习技能",
            "return_to_village": "返回村庄",
            "practice_start": "练习开始！你的对手是",
            "practice_victory": "练习结束！你击败了",
            "practice_reward": "获得20经验值和10金币！",
            "learn_skill_cost": "学习技能需要花费",
            "confirm_learn": "确定要学习吗？(y/n)",
            "cancel_learn": "你取消了学习。",
            "shopkeeper_greeting": "店主：'欢迎光临商店！要买点什么？'",
            "how_many": "购买数量",
            "exit_shop": "离开商店",
            "use_potion_short": "使用药剂",
            "healing_spell_short": "治疗术",
            "merchant_desc": "商人：'旅行者，我有各种好东西，要看看吗？'",
            "buy_equipment": "购买装备",
            "buy_equipment_short": "购买装备",
            "leave_merchant": "离开",
            "merchant_encounter": "遇到商人",
            "mysterious_merchant_encounter": "神秘商人",
            "mysterious_merchant_desc": "神秘商人：'勇敢的冒险者，我有稀有装备出售...'",
            "empty_inventory": "背包为空",
            "enter_item_number": "输入物品编号",
            "return_to_game": "返回游戏",
            "treasure_chest": "宝箱",
            "treasure_chest_desc": "你发现了一个神秘的宝箱，里面可能藏着珍贵的装备！",
            "no_events_yet": "还没有任何冒险记录...",
            "clinic_offer": "医生：'我可以治疗你，恢复",
            "clinic_cost": "治疗费用",
            "confirm_treatment": "确定治疗吗？(y/n)",
            "cancel_treatment": "你取消了治疗。",
            "hp_full": "医生：'你的身体状况很好，不需要治疗。'",
            "treatment_success": "治疗后，你的血量完全恢复了！",
            "elder_advice_title": "长老建议",
            "elder_desc": "长老：'年轻的英雄，让我给你一些建议吧。'",
            "restart_prompt": "是否重新开始游戏"
        }
    
    def _get_english_texts(self):
        """获取英文文本"""
        return {
            "welcome_title": "Welcome to 'Heroes Invincible' Text Adventure Game",
            "welcome_desc1": "Game Instructions:",
            "welcome_desc2": "1. You will play as a hero, adventuring on a 10-grid straight map",
            "welcome_desc3": "2. Each step may trigger random events",
            "welcome_desc4": "3. Reach end to win, zero health to lose",
            "welcome_desc5": "4. Good luck, hero!",
            "continue_prompt": "Press Enter to continue...",
            "hero_creation": "Create Your Hero",
            "enter_name": "Please enter your hero name: ",
            "name_empty": "Name cannot be empty, please re-enter!",
            "game_start": "Game Start",
            "game_over": "Game Over",
            "victory": "Congratulations on Clearing!",
            "restart": "Do you want to restart game? (y/n): ",
            "invalid_choice": "Invalid choice, please enter y or n!",
            "goodbye": "Thank you for playing 'Heroes Invincible', goodbye!",
            "hero_info": "Hero Information",
            "name": "Name",
            "hp": "Health",
            "max_hp": "Max Health",
            "attack": "Attack",
            "defense": "Defense",
            "gold": "Gold",
            "exp": "Experience",
            "level": "Level",
            "potions": "Potions",
            "position": "Position",
            "skills": "Skills",
            "map": "Map",
            "forward": "Move Forward",
            "view_status": "View Status",
            "view_history": "View Adventure History",
            "use_potion": "Use Health Potion",
            "shop": "Shop (spend gold)",
            "choose_action": "Choose your action:",
            "enter_choice": "Please enter your choice",
            "hero_victory": "You defeated",
            "monster_attack": " dealt ",
            "damage": " damage to you",
            "you_attack": "You dealt ",
            "caused_damage": " damage to ",
            "point_damage": " damage",
            "heal": "restored",
            "point_hp": "health points",
            "battle_start": "Battle begins!",
            "battle_victory": "You defeated",
            "got_exp": "You gained",
            "exp_points": "experience points and",
            "gold_coins": "gold coins",
            "level_up": "Congratulations! You reached level",
            "level": "",
            "max_hp_up": "Max HP +20, Attack +5, Defense +2",
            "newbie_village": "Newbie Village",
            "village_welcome": "Welcome to Newbie Village",
            "village_desc": "The village chief looks happy to see you and walks towards you...",
            "chief_speak": "Chief: 'Welcome, young hero! Before you embark on your adventure,",
            "chief_speak2": "       I suggest you get familiar with village first.'",
            "training_ground": "Training Ground",
            "village_shop": "Shop",
            "clinic": "Clinic",
            "chief_home": "Chief's House",
            "leave_village": "Leave Village - Start Adventure",
            "current_location": "Current location: Village Square",
            "areas": "Available areas:",
            "training_ground_desc": "Training Ground - Learn combat skills",
            "shop_desc": "Shop - Purchase basic equipment",
            "clinic_desc": "Clinic - Treat wounds",
            "chief_home_desc": "Chief's House - Get advice",
            "instructor": "Instructor: 'I'm the village combat instructor, I'll teach you some basic skills.'",
            "combat_training": "Learn combat skills (simulated battle, no danger)",
            "return_village": "Return to Village Square",
            "training_start": "Instructor: 'Great! Let's practice.'",
            "training_dummy": "A training dummy appeared...",
            "safe_battle": "This is a danger-free simulated battle!",
            "instructor_tip1": "Instructor: 'When attacking, you can choose normal attack or use skills.'",
            "instructor_tip2": "Instructor: 'Remember to reasonably use potions and healing spells to restore health.'",
            "instructor_tip3": "Instructor: 'Different skills have different effects, use them flexibly!'",
            "training_complete": "Training complete! You gained 5 experience points.",
            "shopkeeper": "Shopkeeper: 'Welcome! I have some useful items for beginners.'",
            "your_gold": "Your gold:",
            "shop_items": "Shop items:",
            "health_potion": "Health Potion",
            "beginner_weapon": "Beginner Weapon +5 Attack",
            "beginner_armor": "Beginner Armor +3 Defense",
            "leave_shop": "Leave Shop",
            "buy_potion": "You bought a health potion!",
            "buy_weapon": "You bought a beginner weapon, attack +5!",
            "buy_armor": "You bought beginner armor, defense +3!",
            "shopkeeper_goodbye": "Shopkeeper: 'Thank you for visiting, come again!'",
            "not_enough_gold": "Not enough gold or invalid choice!",
            "doctor": "Doctor: 'Oh, a new adventurer! Let me give you a check-up.'",
            "doctor_good_health": "Doctor: 'You're in good health, no treatment needed.'",
            "doctor_tip": "Doctor: 'But I still remind you, be careful during adventures!'",
            "doctor_heal": "Doctor: 'Let me help you treat...'",
            "full_heal": "After treatment, your health is fully restored!",
            "elder": "Chief: 'Ah, young hero, do you have many questions to ask?'",
            "advice_adventure": "Adventure advice",
            "advice_level": "About skills and levels",
            "advice_combat": "Combat tips",
            "leave": "Leave",
            "elder_adventure_tip": "Chief: 'Always pay attention to your health during adventures,' '       especially when facing bosses.' '       The map is full of random events,' '       some will bring you benefits, some are dangerous.'",
            "elder_level_tip": "Chief: 'Your attributes will improve with each level up,' '       and every 3 levels you have a chance to learn new skills.' '       Skills will give you an advantage in battle,' '       make good use of them!'",
            "elder_combat_tip": "Chief: 'In battle, you can choose to attack, use potions or cast spells.' '       Monster strength will increase as your level rises,' '       so don't be careless!' '       Bosses are stronger than normal monsters, but rewards are richer.'",
            "elder_goodbye": "Chief: 'Wish you a successful adventure!'",
            "elder_not_hear": "Chief: 'I didn't hear clearly what you want to know.'",
            "leave_village_msg": "Chief: 'Good luck, brave adventurer!'",
            "leave_village_msg2": "You bid farewell to villagers and embarked on adventure path...",
            "step_forward": ">>> You moved forward one step...",
            "mine_trap": "Oh no! You stepped on a mine, losing ",
            "actual_damage": " health points!",
            "dodge_mine": "You keenly detected the mine and dodged in time, taking no damage!",
            "find_bun": "Lucky! You found a magic bun, restoring ",
            "find_spring": "You found a spring of life, fully restoring all health!",
            "find_chest": "You found a treasure chest, gaining ",
            "coins": " gold coins!",
            "merchant": "You encountered a mysterious merchant!",
            "merchant_speak": "Merchant: 'Traveler, I have some good things, want to see?'",
            "no_gold": "Merchant: 'It seems you're short on money, come back next time!'",
            "learn_skill": "Learn Skill",
            "learn_skill_success": "A miracle happened! You learned",
            "skill_name": "] skill!",
            "skill_effect": "Effect: ",
            "find_potion": "You found a health potion!",
            "trap": "You fell into a trap, losing ",
            "dodge_trap": "You keenly detected the trap and dodged in time, taking no damage!",
            "safe_move": "Safe and sound, continue moving forward.",
            "encounter_monster": "You encountered a monster!",
            "encounter_boss": "You encountered a powerful Boss!",
            "poison": "used a health potion, restoring ",
            "use_heal": "cast a healing spell, restoring ",
            "full_hp_no_heal": "Your health is full, no need to heal!",
            "fireball": "You cast a fireball, dealing ",
            "fireball_damage": " damage to ",
            "fireball_crit": "Fireball critical! You dealt ",
            "crit": "Critical! You dealt ",
            "lifesteal": "Lifesteal effect restored ",
            "dodge": "You dodged ",
            "no_damage": "'s attack, taking no damage!",
            "boss_skill_damage": " released a powerful attack, dealing ",
            "game_over_msg": "fell on the adventure path...",
            "try_again": "Keep trying, hero!",
            "victory_msg": "successfully completed the adventure!",
            "final_status": "Final status",
            "real_hero": "You are a true hero!",
            "monsters_defeated": "Monsters defeated",
            "total_gold": "Total gold",
            "skills_learned": "Skills learned",
            "adventure_history": "Adventure History",
            "no_history": "No adventure records yet...",
            "your_journey": "Your adventure history:",
            "damage_defense": "Actual damage",
            "no_victory_heal": "Lifesteal skill kept you at an advantage in battle!",
            "victory_full_heal": "Victory fully restored all health!",
            "victory_heal": "Victory restored ",
            "boss_defeated": "defeated the powerful",
            "hero_medal": "gained [Hero Medal]!",
            "boss_lifesteal": "Lifesteal skill kept you at an advantage in boss battle!",
            "level_up_reward": "Level up reward: You learned",
            "all_skills_learned": "You have learned all skills!",
            "fireball_desc": "Can release powerful magic attacks in battle, also triggers lifesteal",
            "lifesteal_desc": "Each attack restores 30% of damage as health",
            "dodge_desc": "20% chance to completely avoid damage",
            "crit_desc": "15% chance to deal double damage",
            "heal_desc": "Can restore 25-40 health in battle",
            "unknown_effect": "Unknown effect",
            "choose_language": "Please select language",
            "chinese": "中文",
            "english": "English",
            "unit_coins": "",
            "unit_monsters": "",
            "unit_skills": "",
            "block_separator": "="*50,
            "item_separator": ": ",
            "round": "Round",
            "normal_attack": "Normal Attack",
            "remaining": "Remaining",
            "cast_fireball": "Cast Fireball",
            "locked": "Locked",
            "cast_healing": "Cast Healing",
            "invalid_action": "Cannot perform this action, changed to normal attack!",
            "your_hp": "Your health ",
            "monster_hp": "Monster health ",
            "boss_hp": "Boss health ",
            "restore": "Restore",
            "permanent": "Permanent",
            "strength_potion": "Strength Potion",
            "defense_scroll": "Defense Scroll",
            "special_price": "Shop special price",
            "no_potions": "You have no potions!",
            "already_at_end": "You've already reached the end!",
            "danger_encounter": "Danger! Encountered the powerful",
            "boss_battle_start": "Boss battle begins!",
            "boss_victory": "You defeated the powerful",
            "hero_badge": "Got [Hero Badge]!",
            "defeat_boss": "Defeated Boss",
            "lifesteal_advantage": "Lifesteal skill kept you at an advantage in boss battle!",
            "dodge_attack": "You dodged",
            "dodge_success": "'s attack, taking no damage!",
            "healing_spell": "You cast a healing spell, restoring ",
            # 装备系统
            "weapon": "Weapon",
            "armor": "Armor",
            "accessory": "Accessory",
            "none": "None",
            "inventory": "Inventory",
            "inventory_empty": "Your inventory is empty!",
            "equipment_management": "Equipment Management",
            "current_weapon": "Current Weapon",
            "current_armor": "Current Armor",
            "current_accessory": "Current Accessory",
            "current_equipment": "Current Equipment",
            "view_inventory": "View Inventory",
            "equip_item": "Equip Item",
            "unequip_item": "Unequip Item",
            "unequip_weapon": "Unequip Weapon",
            "unequip_armor": "Unequip Armor",
            "unequip_accessory": "Unequip Accessory",
            "return_game": "Return to Game",
            "select_item_to_equip": "Select item number to equip",
            "invalid_item": "Invalid item number!",
            "invalid_item_type": "Invalid equipment type!",
            "no_equipped_item": "No equipment in this slot!",
            "equip_success": "Successfully equipped",
            "unequip_success": "Successfully unequipped",
            "equipment_shop": "Equipment Shop",
            "select_category": "Select product category",
            "weapons": "Weapons",
            "armors": "Armors",
            "accessories": "Accessories",
            "buy": "Buy",
            "back": "Back",
            "buy_success": "Successfully bought",
            "mysterious_merchant": "You encountered a mysterious merchant!",
            "treasure_chest_with_equipment": "You found a shining treasure chest!",
            # 难度和地图系统
            "select_map_difficulty": "Select Map and Difficulty",
            "select_difficulty": "Select Difficulty",
            "difficulty_easy": "Easy",
            "difficulty_normal": "Normal",
            "difficulty_hard": "Hard",
            "difficulty_nightmare": "Nightmare",
            "select_map_type": "Select Map Type",
            "select_map_type": "Select your adventure map type",
            "map_plains": "Plains",
            "map_forest": "Forest",
            "map_desert": "Desert",
            "map_dungeon": "Dungeon",
            "map_mountain": "Mountain",
            "plains_desc": "Flat grasslands, suitable for beginners",
            "forest_desc": "Mysterious forest with many herbs and beasts",
            "desert_desc": "Hot desert with dangerous creatures",
            "dungeon_desc": "Gloomy dungeon with powerful enemies",
            "mountain_desc": "Steep mountains with giants and dragons",
            "difficulty": "Difficulty",
            "map_type": "Map Type",
            "map_length": "Map Length",
            "game_settings": "Game Settings",
            # 新事件文本
            "thorns_damage": "You were scratched by thorns, losing",
            "find_herbs": "You found healing herbs, restoring",
            "dehydration": "You felt severely dehydrated, losing",
            "find_oasis": "You found a desert oasis, restoring",
            "dungeon_trap": "You triggered a dungeon trap, losing",
            "encounter_ghost": "You encountered",
            "mountain_hazard": "You encountered an avalanche/falling rocks, losing",
            "find_gem": "You found gems, gaining",
            "ghost_drop_equipment": "The ghost dropped equipment when dissipating!",
            "ghost_dissipate": "The ghost dissipates into the void...",
            "encounter_ghost": "You encountered a ghost!",
            # Newbie village additional texts
            "village_clinic": "Clinic",
            "elder_advice_short": "Elder's Advice",
            "start_adventure": "Start Adventure",
            "hp_recovered": "Your health has been fully restored!",
            "training_desc": "The training ground allows you to practice combat skills and gain experience.",
            "practice_combat": "Practice Combat",
            "learn_skill_short": "Learn Skill",
            "return_to_village": "Return to Village",
            "practice_start": "Practice begins! Your opponent is",
            "practice_victory": "Practice complete! You defeated",
            "practice_reward": "Gained 20 experience and 10 gold!",
            "learn_skill_cost": "Learning a skill costs",
            "confirm_learn": "Confirm learning? (y/n)",
            "cancel_learn": "You cancelled learning.",
            "shopkeeper_greeting": "Shopkeeper: 'Welcome to my shop! What would you like to buy?'",
            "how_many": "Quantity",
            "exit_shop": "Exit Shop",
            "use_potion_short": "Use Potion",
            "healing_spell_short": "Healing Spell",
            "merchant_desc": "Merchant: 'Traveler, I have many fine goods, want to take a look?'",
            "buy_equipment": "Buy Equipment",
            "buy_equipment_short": "Buy Equipment",
            "leave_merchant": "Leave",
            "merchant_encounter": "Meet Merchant",
            "mysterious_merchant_encounter": "Mysterious Merchant",
            "mysterious_merchant_desc": "Mysterious Merchant: 'Brave adventurer, I have rare equipment for sale...'",
            "empty_inventory": "Inventory is empty",
            "enter_item_number": "Enter item number",
            "return_to_game": "Return to Game",
            "treasure_chest": "Treasure Chest",
            "treasure_chest_desc": "You found a mysterious chest, which might contain precious equipment!",
            "no_events_yet": "No adventure records yet...",
            "clinic_offer": "Doctor: 'I can heal you, restoring",
            "clinic_cost": "Treatment cost",
            "confirm_treatment": "Confirm treatment? (y/n)",
            "cancel_treatment": "You cancelled treatment.",
            "hp_full": "Doctor: 'You are in good health, no treatment needed.'",
            "treatment_success": "After treatment, your health is fully restored!",
            "elder_advice_title": "Elder's Advice",
            "elder_desc": "Elder: 'Young hero, let me give you some advice.'",
            "restart_prompt": "Do you want to restart the game"
        }
    
    def get_text(self, key):
        """获取指定键的文本"""
        return self.texts.get(key, key)